---
- hosts: esxi
  gather_facts: no
  roles:
    - role: create_vm
      vars: #Variables pour Survey Variables de Semaphore
        name: "{{ vm_name }}"
        hostname: "{{ esxi_hostname }}"
        datastore: "{{ datastore_name }}"
        hostname: "{{ vm_hostname }}"
        password: "{{ vm_pwd }}"
        ip: "{{ vm_ip }}"
