---
- hosts: esxi
  gather_facts: no
  tasks:
    - name: Set static IP address on Windows VM via WinRM
      win_shell: |
        Set-NetIPAddress -InterfaceAlias "Ethernet0" -IPAddress "192.168.25.12" -PrefixLength 24 /force
        Set-DnsClientServerAddress -InterfaceAlias "Ethernet0" -ServerAddresses ("192.168.25.101","8.8.8.8")
      vars:
        ansible_host: "{{ default_ip }}"
        ansible_user: "{{ vm_user }}"
        ansible_password: "{{ vm_pwd }}"
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore

