---
- hosts: esxi
  gather_facts: no
  tasks:
    - name: Set static IP address on Windows VM via WinRM
      win_shell: |
        $NetIndex = (Get-NetIPAddress -InterfaceAlias "Ethernet*").InterfaceIndex
        $NewNetIndex = $NetIndex +"1"
        New-NetIPAddress -InterfaceIndex $NewNetIndex -IPAddress {{ vm_ip }} -PrefixLength 24 -DefaultGateway '192.168.25.254'
        Set-DnsClientServerAddress -InterfaceIndex $NewNetIndex -ServerAddresses ("192.168.25.101","8.8.8.8")
        #(Get-NetIPAddress -InterfaceIndex $NetIndex) | Remove-NetIPAddress -Force
      vars:
        ansible_host: "{{ default_ip }}"
        ansible_user: "{{ vm_user }}"
        ansible_password: "{{ vm_pwd }}"
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore

