---
- hosts: esxi
  gather_facts: no
  tasks:
    - name: Set static IP on Windows VM
      community.vmware.vmware_guest:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_pass }}"
        validate_certs: no
        name: "{{ vm_name }}"
        networks:
          - name: LAN
            type: static
            ip: "{{ vm_ip }}"
            netmask: 255.255.255.0
            gateway: 192.168.25.254
            dns_servers: 8.8.8.8
