---
- name: Mount VMware Tools ISO and install on Windows VM
  hosts: esxi
  gather_facts: no
  tasks:
  
  - name: Attach VMware Tools ISO to the VM
    community.vmware.vmware_guest:
      hostname: "{{ esxi_hostname }}"
      username: "{{ esxi_user }}"
      password: "{{ esxi_pass }}"
      datastore: "{{ datastore_name }}"
      folder: "/"
      name: "{{ vm_name }}"
      cdrom:
        - controller_number: 1
          unit_number: 0
          state: present
          type: iso
          iso_path: '[] /usr/lib/vmware/isoimages/windows.iso'
      validate_certs: no
    delegate_to: localhost
    
  - name: Wait for VM to mount ISO
    pause:
      seconds: 5  # Temps d'attente pour que l'ISO soit monté
  
  - name: Run VMware Tools installation using win_shell
    win_powershell: |
        Start-Process -Wait -FilePath "D:\setup64.exe" -ArgumentList "/S /v /qn REBOOT=R"
