---
- hosts: esxi
  gather_facts: no
  tasks:
    - name: Set static IP address on Windows VM via WinRM
      win_shell: |
        Get-NetIPAddress -InterfaceIndex 3 | Remove-NetIPAddress 
        New-NetIPAddress -InterfaceIndex 3 -IPAddress {{ vm_ip }} -PrefixLength 24 -DefaultGateway '192.168.25.254'
        Set-DnsClientServerAddress -InterfaceIndex 3 -ServerAddresses ("192.168.25.101","8.8.8.8")
      vars:
        ansible_host: "{{ default_ip }}"
        ansible_user: "{{ vm_user }}"
        ansible_password: "{{ vm_pwd }}"
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore

