---
- hosts: esxi
  gather_facts: no
  tasks:
    - name: Install VMware Tools via Guest Operations
      community.vmware.vmware_guest_tools:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_pass }}"
        validate_certs: no
        name: "{{ vm_name }}"
        command: |
          Start-Process -Wait -FilePath "D:\setup64.exe" -ArgumentList "/S /v /qn REBOOT=R"
        timeout: 300  # Temps d'attente pour l'exécution de la commande
      delegate_to: localhost
