---
- name: Deploy Ubuntu 22.04 on ESXi with dynamic or static IP allocation
  hosts: esxi
  gather_facts: no
  vars:
    preseed_url: "http://your_web_server/ubuntu-preseed.cfg"
    ip_allocation_policy: "static"  # Can be 'dynamic' or 'static'
    static_ip: "192.168.25.10"  # Défini dynamiquement ou via une variable d'inventaire
    netmask: "255.255.255.0"
    gateway: "192.168.25.254"  # Assurez-vous que c'est la bonne passerelle pour votre réseau
    dns_servers: "8.8.8.8 8.8.4.4"
    vm_name: "ubuntu-22-04"
    iso_path: "[datastore 1] ISO/ubuntu-22.04.4-live-server-amd64.iso"  # Ajustez selon votre environnement
    
  tasks:
    - name: Create VM
      community.vmware.vmware_guest:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_pass }}"
        validate_certs: no
        datastore: "{{ datastore_name }}"
        folder: "/"
        name: "{{ vm_name }}"
        state: poweredon
        guest_id: ubuntu64Guest
        hardware:
          num_cpus: 2
          memory_mb: 4096
        disk:
          - size_gb: 20
            type: thin
            datastore: "{{ datastore_name }}"
        cdrom:
          - controller_number: 0
            unit_number: 0
            state: present
            type: iso
            iso_path: "{{ iso_path }}"
        networks:
          - name: LAN
            device_type: vmxnet3
        wait_for_ip_address: yes
        customization:
          dns_servers:
            - 8.8.8.8
            - 8.8.4.4
      delegate_to: localhost
      register: deploy_vm

    - name: Display VM IP
      debug:
        var: deploy_vm.instance.ipv4

    - name: Wait for SSH to become available
      wait_for:
        host: "{{ deploy_vm.instance.ipv4 }}"
        port: 22
        delay: 10
        timeout: 300
      delegate_to: localhost

- name: Configure Ubuntu server
  hosts: "{{ hostvars['localhost']['deploy_vm']['instance']['ipv4'] }}"
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Install common packages
      apt:
        name:
          - vim
          - htop
          - curl
          - git
        state: present

    - name: Configure firewall
      ufw:
        rule: allow
        port: "22"
        proto: tcp

    - name: Enable firewall
      ufw:
        state: enabled

    - name: Set timezone
      timezone:
        name: Europe/Paris
