---
# Tâche pour créer la VM mais en état éteinte
- name: Create a new virtual machine (powered off)
  community.vmware.vmware_guest:
    hostname: "{{ esxi_hostname }}"
    username: "{{ esxi_user }}"
    password: "{{ esxi_pass }}"
    datastore: "{{ datastore_name }}"
    folder: "/"
    validate_certs: no
    name: "{{ vm_name }}"
    guest_id: windows9Server64Guest
    state: powered-on  # Créer la VM mais la laisser éteinte
    hardware:
      boot_firmware: efi
      num_cpus: 2
      memory_mb: 4096
      scsi: paravirtual
    cdrom:
      - controller_number: 1
        unit_number: 0
        state: present
        type: iso
        iso_path: "{{ iso_path }}"
    disk:
      - size_gb: 40
        type: thin
        datastore: "{{ datastore_name }}"
        controller_type: 'nvme'
        controller_number: 0
        unit_number: 0
    networks:
      - name: LAN
        type: static
        device_type: e1000e
        ip: "{{ vm_ip }}"
        netmask: 255.255.255.0
        gateway: 192.168.25.254
        dns_servers: 8.8.8.8
    wait_for_ip_address: no
  delegate_to: localhost

# Ajouter un contrôleur USB à la VM
- name: Add USB controller to VM
  community.vmware.vmware_guest_controller:
    hostname: "{{ esxi_hostname }}"
    username: "{{ esxi_user }}"
    password: "{{ esxi_pass }}"
    name: "{{ vm_name }}"
    controllers:
      - state: present
        type: usb3
    validate_certs: no
  delegate_to: localhost

# Pause pour laisser le temps d'installation des VMware Tools
- name: Wait for VMware Tools to be installed
  pause:
    seconds: 300  # Ajuster selon le temps nécessaire


- name: Attach VMware Tools ISO to the VM
  community.vmware.vmware_guest_cdrom:
    hostname: "{{ esxi_hostname }}"
    username: "{{ esxi_user }}"
    password: "{{ esxi_pass }}"
    validate_certs: no
    name: "{{ vm_name }}"  # Nom de la VM cible
    state: present
    iso_path: [datastore 1] ISO/Win_Server_2019_Custom.iso  # Chemin vers l'ISO des VMware Tools
    controller_number: 1
    unit_number: 0


