#
---
- name: Create a new virtual machine
  community.vmware.vmware_guest:
    hostname: "{{ esxi_hostname }}"
    username: "{{ esxi_user }}"
    password: "{{ esxi_pass }}"
    datastore: "{{ datastore_name }}"
    folder: "/"
    validate_certs: no
    name: "{{ vm_name }}"
    guest_id: windows9Server64Guest
    state: poweredon
    hardware:
      boot_firmware: efi
      num_cpus: 2
      memory_mb: 4096
      scsi: paravirtual
    cdrom:
      - controller_number: 0
        unit_number: 0
        state: present
        type: iso
        iso_path: "{{ iso_path }}"
    networks:
      - name: LAN
        type: static
        ip: "{{ vm_ip }}"
        netmask: 255.255.255.0
        gateway: 192.168.25.254
        dns_servers: 8.8.8.8
    disk:
      - size_gb: 40
        type: thin
        datastore: Datastore
        controller_type: 'nvme'
        controller_number: 0
        unit_number: 0
    wait_for_ip_address: yes
  delegate_to: localhost
