# tasks file for roles/create_vm
---
- name: Create a new virtual machine
  community.vmware.vmware_guest:
    hostname: "{{ esxi_hostname }}"
    username: "{{ esxi_user }}"
    password: "{{ esxi_pass }}"
    validate_certs: no
    name: "{{ vm_name }}"
    template: "{{ vm_template_name }}"
    folder: "/"
    datacenter: "{{ datacenter_name }}"
    datastore: "Datastore Test"
    cluster: "{{ cluster_name }}"
    #esxi_hostname: "{{ esxi_host }}"
    state: poweredon
    #guest_id: windows9Server64Guest
    hardware:
      num_cpus: 2
      memory_mb: 4096
      scsi: paravirtual
    networks:
      - name: LAN
        type: static
        ip: "{{ vm_ip }}"
        netmask: 255.255.255.0
        gateway: 192.168.50.254
        dns_servers: 192.168.50.101
    disk:
      - size_gb: 40
        type: thin
        datastore: Datastore ISCSI
    wait_for_ip_address: yes
  delegate_to: localhost
